# Generated by Django 2.1.5 on 2019-02-10 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individualprojectspage',
            old_name='category',
            new_name='technology_used',
        ),
    ]
