# Generated by Django 2.1.5 on 2019-02-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190210_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualprojectspage',
            name='technology_used',
            field=models.CharField(blank=True, choices=[('wordpress', 'WordPress'), ('prestashop', 'Prestashop'), ('django', 'Django'), ('comingsoon', 'Comingsoon')], max_length=255, null=True),
        ),
    ]
