# Generated by Django 2.1.5 on 2019-02-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20190210_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualprojectspage',
            name='technology_used',
            field=models.CharField(blank=True, choices=[('WORDPRESS', 'WordPress'), ('PRESTASHOP', 'Prestashop'), ('DJANGO', 'Django')], max_length=255, null=True),
        ),
    ]
