# Generated by Django 2.1.5 on 2019-02-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20190210_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualprojectspage',
            name='technology_used',
            field=models.CharField(choices=[('WORDPRESS', 'WordPress'), ('PRESTASHOP', 'Prestashop'), ('DJANGO', 'Django')], default='WP', max_length=255),
        ),
    ]
