# Generated by Django 2.1.5 on 2019-02-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20190210_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualprojectspage',
            name='technology_used',
            field=models.CharField(blank=True, choices=[('WP', 'WordPress'), ('PS', 'Prestashop'), ('DJ', 'Django')], max_length=255),
        ),
    ]
