# Generated by Django 2.1.5 on 2019-02-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20190210_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualprojectspage',
            name='technology_used',
            field=models.CharField(choices=[('WP', 'WordPress'), ('PS', 'Prestashop'), ('DJ', 'Django')], default='WP', max_length=255),
        ),
    ]
