# Generated by Django 2.1.5 on 2019-02-10 11:13

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190210_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='intro_left',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='intro_right',
        ),
        migrations.AddField(
            model_name='portfoliosettings',
            name='intro_heading',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfoliosettings',
            name='intro_left',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='portfoliosettings',
            name='intro_right',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='portfoliosettings',
            name='intro_sub_heading',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
