# Generated by Django 2.1.5 on 2019-02-10 11:43

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190210_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='intro_heading1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_left1',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_right1',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_sub_heading1',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
