# Generated by Django 2.1.5 on 2019-02-10 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190210_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='intro_heading1',
            new_name='intro_heading',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='intro_left1',
            new_name='intro_left',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='intro_right1',
            new_name='intro_right',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='intro_sub_heading1',
            new_name='intro_sub_heading',
        ),
        migrations.RemoveField(
            model_name='portfoliosettings',
            name='intro_heading',
        ),
        migrations.RemoveField(
            model_name='portfoliosettings',
            name='intro_left',
        ),
        migrations.RemoveField(
            model_name='portfoliosettings',
            name='intro_right',
        ),
        migrations.RemoveField(
            model_name='portfoliosettings',
            name='intro_sub_heading',
        ),
    ]
