# Generated by Django 2.1.5 on 2019-02-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190210_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliosettings',
            name='stat_description_1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfoliosettings',
            name='stat_description_2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfoliosettings',
            name='stat_description_3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfoliosettings',
            name='stat_description_4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfoliosettings',
            name='stat_number_1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='portfoliosettings',
            name='stat_number_2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='portfoliosettings',
            name='stat_number_3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='portfoliosettings',
            name='stat_number_4',
            field=models.IntegerField(null=True),
        ),
    ]
